name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install ROS
      run: |
        sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list'
        wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        sudo apt update
        sudo apt install ros-melodic-desktop-full
        source /opt/ros/melodic/setup.bash
        sudo apt install python-rosdep
        sudo rosdep init
        rosdep update

    - name: Install catkin
      run: |
        sudo apt install python-pip
        sudo pip install -U catkin_tools
        
    - name: Catkin build
      run: |
        cd ros
        source /opt/ros/melodic/setup.bash 
        catkin build
